<a href="https://colab.research.google.com/github/aanchan1/social-network-ads-analysis/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Social_Networks_Ads.csv

**Importing the libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Importing the dataset**

In [ ]:
data = pd.read_csv('Social_Network_Ads.csv')


In [ ]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

**Splitting the dataset into the Training set and Test set**

In [ ]:
X=data.iloc[:,2:4]
print(X.shape)
y=data.iloc[:,-1].values
print(y.shape)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
X_train.shape


(400, 2)
(400,)


(280, 2)

In [ ]:
X_test.shape


(120, 2)

In [ ]:
y_train.shape

(280,)

In [ ]:
y_test.shape

(120,)

**Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_train

array([[-0.77727984,  1.37177947],
       [-0.30538401, -1.28240391],
       [ 0.63840764, -1.07823596],
       [-0.21100485, -0.26156415],
       [-0.11662568,  2.18845128],
       [ 1.77095762, -1.04906911],
       [-0.11662568, -1.04906911],
       [ 0.7327868 , -1.19490336],
       [ 1.2990618 ,  1.31344577],
       [-0.30538401, -1.42823816],
       [ 0.63840764,  1.80928223],
       [-0.77727984,  0.29260601],
       [-0.11662568,  0.23427231],
       [ 0.35527014, -0.43656525],
       [-0.21100485,  2.18845128],
       [-1.62669233, -1.54490556],
       [ 1.11030347, -1.42823816],
       [ 0.16651181, -0.290731  ],
       [ 0.35527014,  0.61344136],
       [ 0.26089098, -0.1740636 ],
       [-0.39976318,  1.25511207],
       [-0.87165901, -0.6407332 ],
       [ 0.63840764, -1.25323706],
       [ 0.26089098, -0.26156415],
       [-1.62669233,  0.55510766],
       [-1.437934  , -0.61156635],
       [-0.58852151,  1.48844688],
       [ 0.35527014,  1.13844467],
       [-0.11662568,

In [ ]:
X_test = scaler.fit_transform(X_test)
X_test


array([[ 0.06971821,  0.10317306],
       [ 0.56770543,  0.222794  ],
       [ 0.56770543, -0.04635311],
       [-0.72706134,  2.28625519],
       [ 1.26488754,  0.07326782],
       [ 1.56367987, -1.00332062],
       [-1.12545112, -1.1528468 ],
       [-1.02585367, -1.18275203],
       [ 1.16529009, -1.1528468 ],
       [ 0.16931565,  0.25269923],
       [ 0.2689131 , -0.3753107 ],
       [ 0.16931565,  1.23957198],
       [-0.02987923,  1.59843479],
       [-0.12947668, -0.64445781],
       [ 1.76287476, -1.36218344],
       [-0.42826901,  1.89748714],
       [-0.92625623, -0.40521593],
       [ 2.36045942,  0.9106144 ],
       [ 0.36851054,  0.10317306],
       [-0.82665878, -0.82388922],
       [ 0.06971821, -0.04635311],
       [ 2.36045942,  1.0900458 ],
       [ 1.8624722 , -0.97341539],
       [-0.12947668, -0.3753107 ],
       [-0.12947668, -0.5547421 ],
       [-1.42424345, -0.49493163],
       [ 0.66730287,  1.20966674],
       [ 0.56770543,  2.31616043],
       [ 0.06971821,

In [ ]:
# scaling the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Fitting K-NN to the Training set**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train,y_train)

KNeighborsClassifier()

**Predicting the Test set results**

In [ ]:
y_predict = classifier.predict(X_test)
y_predict

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0])

**Making the Confusion Matrix**

In [ ]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
print(confusion_matrix(y_test,y_predict))
print(accuracy_score(y_test,y_predict))


[[77  6]
 [ 4 33]]
0.9166666666666666


In [ ]:
from sklearn.metrics import precision_score
print("Precision: {0}".format(precision_score(y_test, classifier.predict(X_test))))
from sklearn.metrics import recall_score
print("Recall:", round(recall_score(y_test, classifier.predict(X_test)), 2))
from sklearn.metrics import roc_auc_score,accuracy_score
print('auroc',roc_auc_score(y_test, classifier.predict_proba(X_test)[:,1]))
print("Accuracy:",accuracy_score(y_test, y_predict))

Precision: 0.8461538461538461
Recall: 0.89
auroc 0.9560403777271247
Accuracy: 0.9166666666666666
